# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from meta import filemeta_pb2 as meta_dot_filemeta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='serverApi',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\tserverApi\x1a\x13meta/filemeta.proto\":\n\x0cWriteRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05\x62size\x18\x02 \x01(\x04\x12\r\n\x05umask\x18\x03 \x01(\r\"0\n\rWriteResponse\x12\x1f\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x0f.meta.FileChunk\"\x1b\n\x0bReadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"/\n\x0cReadResponse\x12\x1f\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x0f.meta.FileChunk\"\x1c\n\x0c\x45xistRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1f\n\rExistResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\xc0\x01\n\x07\x46ileAPI\x12<\n\x05Write\x12\x17.serverApi.WriteRequest\x1a\x18.serverApi.WriteResponse\"\x00\x12\x39\n\x04Read\x12\x16.serverApi.ReadRequest\x1a\x17.serverApi.ReadResponse\"\x00\x12<\n\x05\x45xist\x12\x17.serverApi.ExistRequest\x1a\x18.serverApi.ExistResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[meta_dot_filemeta__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WRITEREQUEST = _descriptor.Descriptor(
  name='WriteRequest',
  full_name='serverApi.WriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='serverApi.WriteRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bsize', full_name='serverApi.WriteRequest.bsize', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='umask', full_name='serverApi.WriteRequest.umask', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=103,
)


_WRITERESPONSE = _descriptor.Descriptor(
  name='WriteResponse',
  full_name='serverApi.WriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunks', full_name='serverApi.WriteResponse.chunks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=153,
)


_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='serverApi.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='serverApi.ReadRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=182,
)


_READRESPONSE = _descriptor.Descriptor(
  name='ReadResponse',
  full_name='serverApi.ReadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunks', full_name='serverApi.ReadResponse.chunks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=231,
)


_EXISTREQUEST = _descriptor.Descriptor(
  name='ExistRequest',
  full_name='serverApi.ExistRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='serverApi.ExistRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=261,
)


_EXISTRESPONSE = _descriptor.Descriptor(
  name='ExistResponse',
  full_name='serverApi.ExistResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exists', full_name='serverApi.ExistResponse.exists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=294,
)

_WRITERESPONSE.fields_by_name['chunks'].message_type = meta_dot_filemeta__pb2._FILECHUNK
_READRESPONSE.fields_by_name['chunks'].message_type = meta_dot_filemeta__pb2._FILECHUNK
DESCRIPTOR.message_types_by_name['WriteRequest'] = _WRITEREQUEST
DESCRIPTOR.message_types_by_name['WriteResponse'] = _WRITERESPONSE
DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['ReadResponse'] = _READRESPONSE
DESCRIPTOR.message_types_by_name['ExistRequest'] = _EXISTREQUEST
DESCRIPTOR.message_types_by_name['ExistResponse'] = _EXISTRESPONSE

WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), dict(
  DESCRIPTOR = _WRITEREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:serverApi.WriteRequest)
  ))
_sym_db.RegisterMessage(WriteRequest)

WriteResponse = _reflection.GeneratedProtocolMessageType('WriteResponse', (_message.Message,), dict(
  DESCRIPTOR = _WRITERESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:serverApi.WriteResponse)
  ))
_sym_db.RegisterMessage(WriteResponse)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), dict(
  DESCRIPTOR = _READREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:serverApi.ReadRequest)
  ))
_sym_db.RegisterMessage(ReadRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), dict(
  DESCRIPTOR = _READRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:serverApi.ReadResponse)
  ))
_sym_db.RegisterMessage(ReadResponse)

ExistRequest = _reflection.GeneratedProtocolMessageType('ExistRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXISTREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:serverApi.ExistRequest)
  ))
_sym_db.RegisterMessage(ExistRequest)

ExistResponse = _reflection.GeneratedProtocolMessageType('ExistResponse', (_message.Message,), dict(
  DESCRIPTOR = _EXISTRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:serverApi.ExistResponse)
  ))
_sym_db.RegisterMessage(ExistResponse)


import abc
import six
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

class BetaFileAPIServicer(object):
  def Write(self, request, context):
    """send a write request
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def Read(self, request, context):
    """send a read request
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def Exist(self, request, context):
    """send a request to see if a file/dir exists
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)

class BetaFileAPIStub(object):
  def Write(self, request, timeout):
    """send a write request
    """
    raise NotImplementedError()
  Write.future = None
  def Read(self, request, timeout):
    """send a read request
    """
    raise NotImplementedError()
  Read.future = None
  def Exist(self, request, timeout):
    """send a request to see if a file/dir exists
    """
    raise NotImplementedError()
  Exist.future = None

def beta_create_FileAPI_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import api_pb2
  import api_pb2
  import api_pb2
  import api_pb2
  import api_pb2
  import api_pb2
  request_deserializers = {
    ('serverApi.FileAPI', 'Exist'): api_pb2.ExistRequest.FromString,
    ('serverApi.FileAPI', 'Read'): api_pb2.ReadRequest.FromString,
    ('serverApi.FileAPI', 'Write'): api_pb2.WriteRequest.FromString,
  }
  response_serializers = {
    ('serverApi.FileAPI', 'Exist'): api_pb2.ExistResponse.SerializeToString,
    ('serverApi.FileAPI', 'Read'): api_pb2.ReadResponse.SerializeToString,
    ('serverApi.FileAPI', 'Write'): api_pb2.WriteResponse.SerializeToString,
  }
  method_implementations = {
    ('serverApi.FileAPI', 'Exist'): face_utilities.unary_unary_inline(servicer.Exist),
    ('serverApi.FileAPI', 'Read'): face_utilities.unary_unary_inline(servicer.Read),
    ('serverApi.FileAPI', 'Write'): face_utilities.unary_unary_inline(servicer.Write),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_FileAPI_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import api_pb2
  import api_pb2
  import api_pb2
  import api_pb2
  import api_pb2
  import api_pb2
  request_serializers = {
    ('serverApi.FileAPI', 'Exist'): api_pb2.ExistRequest.SerializeToString,
    ('serverApi.FileAPI', 'Read'): api_pb2.ReadRequest.SerializeToString,
    ('serverApi.FileAPI', 'Write'): api_pb2.WriteRequest.SerializeToString,
  }
  response_deserializers = {
    ('serverApi.FileAPI', 'Exist'): api_pb2.ExistResponse.FromString,
    ('serverApi.FileAPI', 'Read'): api_pb2.ReadResponse.FromString,
    ('serverApi.FileAPI', 'Write'): api_pb2.WriteResponse.FromString,
  }
  cardinalities = {
    'Exist': cardinality.Cardinality.UNARY_UNARY,
    'Read': cardinality.Cardinality.UNARY_UNARY,
    'Write': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'serverApi.FileAPI', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
