# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta/filemeta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meta/filemeta.proto',
  package='meta',
  syntax='proto3',
  serialized_pb=_b('\n\x13meta/filemeta.proto\x12\x04meta\"9\n\tModifiers\x12\x0c\n\x04read\x18\x01 \x01(\r\x12\r\n\x05write\x18\x02 \x01(\r\x12\x0f\n\x07\x65xecute\x18\x03 \x01(\r\"m\n\nFileAccess\x12\x1e\n\x05owner\x18\x01 \x01(\x0b\x32\x0f.meta.Modifiers\x12\x1f\n\x06ugroup\x18\x02 \x01(\x0b\x32\x0f.meta.Modifiers\x12\x1e\n\x05other\x18\x03 \x01(\x0b\x32\x0f.meta.Modifiers\"F\n\tFileChunk\x12\x0c\n\x04\x66qdn\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x05\x12\x10\n\x08\x62ytesize\x18\x03 \x01(\x03\x12\x0c\n\x04path\x18\x04 \x01(\t\"]\n\x04\x46ile\x12\x11\n\treplicaID\x18\x01 \x01(\x05\x12\x1f\n\x06\x63hunks\x18\x02 \x03(\x0b\x32\x0f.meta.FileChunk\x12!\n\x07\x66\x61\x63\x63\x65ss\x18\x03 \x01(\x0b\x32\x10.meta.FileAccess\"4\n\x05\x44\x46ile\x12\x10\n\x08repilcas\x18\x01 \x01(\x05\x12\x19\n\x05\x66iles\x18\x02 \x03(\x0b\x32\n.meta.File\"u\n\tDirectory\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t\x12\x19\n\x05\x66iles\x18\x02 \x03(\x0b\x32\n.meta.File\x12\x1d\n\x04\x64irs\x18\x03 \x03(\x0b\x32\x0f.meta.Directory\x12!\n\x07\x64\x61\x63\x63\x65ss\x18\x04 \x01(\x0b\x32\x10.meta.FileAccessb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODIFIERS = _descriptor.Descriptor(
  name='Modifiers',
  full_name='meta.Modifiers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read', full_name='meta.Modifiers.read', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write', full_name='meta.Modifiers.write', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='execute', full_name='meta.Modifiers.execute', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=86,
)


_FILEACCESS = _descriptor.Descriptor(
  name='FileAccess',
  full_name='meta.FileAccess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='meta.FileAccess.owner', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ugroup', full_name='meta.FileAccess.ugroup', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='other', full_name='meta.FileAccess.other', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=197,
)


_FILECHUNK = _descriptor.Descriptor(
  name='FileChunk',
  full_name='meta.FileChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fqdn', full_name='meta.FileChunk.fqdn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='meta.FileChunk.seq', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytesize', full_name='meta.FileChunk.bytesize', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='meta.FileChunk.path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=269,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='meta.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replicaID', full_name='meta.File.replicaID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunks', full_name='meta.File.chunks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='faccess', full_name='meta.File.faccess', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=364,
)


_DFILE = _descriptor.Descriptor(
  name='DFile',
  full_name='meta.DFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repilcas', full_name='meta.DFile.repilcas', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='files', full_name='meta.DFile.files', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=418,
)


_DIRECTORY = _descriptor.Descriptor(
  name='Directory',
  full_name='meta.Directory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='meta.Directory.dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='files', full_name='meta.Directory.files', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dirs', full_name='meta.Directory.dirs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='daccess', full_name='meta.Directory.daccess', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=537,
)

_FILEACCESS.fields_by_name['owner'].message_type = _MODIFIERS
_FILEACCESS.fields_by_name['ugroup'].message_type = _MODIFIERS
_FILEACCESS.fields_by_name['other'].message_type = _MODIFIERS
_FILE.fields_by_name['chunks'].message_type = _FILECHUNK
_FILE.fields_by_name['faccess'].message_type = _FILEACCESS
_DFILE.fields_by_name['files'].message_type = _FILE
_DIRECTORY.fields_by_name['files'].message_type = _FILE
_DIRECTORY.fields_by_name['dirs'].message_type = _DIRECTORY
_DIRECTORY.fields_by_name['daccess'].message_type = _FILEACCESS
DESCRIPTOR.message_types_by_name['Modifiers'] = _MODIFIERS
DESCRIPTOR.message_types_by_name['FileAccess'] = _FILEACCESS
DESCRIPTOR.message_types_by_name['FileChunk'] = _FILECHUNK
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['DFile'] = _DFILE
DESCRIPTOR.message_types_by_name['Directory'] = _DIRECTORY

Modifiers = _reflection.GeneratedProtocolMessageType('Modifiers', (_message.Message,), dict(
  DESCRIPTOR = _MODIFIERS,
  __module__ = 'meta.filemeta_pb2'
  # @@protoc_insertion_point(class_scope:meta.Modifiers)
  ))
_sym_db.RegisterMessage(Modifiers)

FileAccess = _reflection.GeneratedProtocolMessageType('FileAccess', (_message.Message,), dict(
  DESCRIPTOR = _FILEACCESS,
  __module__ = 'meta.filemeta_pb2'
  # @@protoc_insertion_point(class_scope:meta.FileAccess)
  ))
_sym_db.RegisterMessage(FileAccess)

FileChunk = _reflection.GeneratedProtocolMessageType('FileChunk', (_message.Message,), dict(
  DESCRIPTOR = _FILECHUNK,
  __module__ = 'meta.filemeta_pb2'
  # @@protoc_insertion_point(class_scope:meta.FileChunk)
  ))
_sym_db.RegisterMessage(FileChunk)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'meta.filemeta_pb2'
  # @@protoc_insertion_point(class_scope:meta.File)
  ))
_sym_db.RegisterMessage(File)

DFile = _reflection.GeneratedProtocolMessageType('DFile', (_message.Message,), dict(
  DESCRIPTOR = _DFILE,
  __module__ = 'meta.filemeta_pb2'
  # @@protoc_insertion_point(class_scope:meta.DFile)
  ))
_sym_db.RegisterMessage(DFile)

Directory = _reflection.GeneratedProtocolMessageType('Directory', (_message.Message,), dict(
  DESCRIPTOR = _DIRECTORY,
  __module__ = 'meta.filemeta_pb2'
  # @@protoc_insertion_point(class_scope:meta.Directory)
  ))
_sym_db.RegisterMessage(Directory)


import abc
import six
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
